#!/bin/bash
#PBS -N test_openvla_modern-cont
#PBS -l select=1:ncpus=4:ngpus=1:mem=32gb
#PBS -l walltime=02:00:00
#PBS -o logs/test_openvla_modern-cont.out
#PBS -e logs/test_openvla_modern-cont.err

cd $PBS_O_WORKDIR

# Run the script using the Singularity container with environment variables set inside the container
singularity exec --nv --cleanenv --overlay containers/overlay_2000_2.img containers/modern_cont.sif bash -c "
    export PYTHONUSERBASE=$HOME/.local;
    export PYTHONPATH=/usr/local/lib/python3.12/dist-packages:\$PYTHONUSERBASE/lib/python3.12/site-packages:\$PYTHONPATH;
    export PATH=\$PYTHONUSERBASE/bin:\$PATH;
    python3 -c 'import torch, transformers, timm, numpy; print(\"All packages loaded successfully!\")' || exit 1;
    python3 scripts/test_openvla_modern-cont.py
"
